{% set name = "pyxtal" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyxtal-{{ version }}.tar.gz
  sha256: 39542b30dea76e60d8c51383f8bee475d0c9d833ebf3196bca627173a94ed330

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.12
    - psutil
    - pyocse >=0.1.1
    - vasprun-xml >=1.0.4
    - numpy >=1.26,<2
    - typing-extensions >=4.12
    - python >={{ python_min }},<3.13a0
    - spglib >=2.5.0
    - pymatgen >=2024.3.1
    - pandas >=2.0.2
    - networkx >=2.3
    - ase >=3.23.0
    - scipy >=1.7.3
    - importlib-metadata >=1.4
    - pyshtools >=4.10.3

test:
  imports:
    - pyxtal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qzhu2017/PyXtal
  summary: Python code for generation of crystal structures based on symmetry constraints.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
