{% set name = "pyxtal" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyxtal-{{ version }}.tar.gz
  sha256: dee22d9623f10362e47b9f09622c875c08cbe202e074f2188be6a0736464c2b5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - spglib >=2.5.0
    - pymatgen >=2024.3.1
    - pandas >=2.0.2
    - networkx >=2.3
    - ase >=3.23.0
    - scipy >=1.7.3
    - vasprun-xml >=1.0.4
    - importlib-metadata >=1.4
    - typing_extensions >=4.12
    - pyocse >=0.1.1
    - psutil

test:
  imports:
    - pyxtal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qzhu2017/PyXtal
  summary: Python code for generation of crystal structures based on symmetry constraints.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
