{% set name = "pyxtal" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyxtal-{{ version }}.tar.gz
  sha256: 5e590f0f7a3d23535e98a379ce0e9fc34f07444e8e52ad98bae3980858ef6fd7

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python <=3.12,>=3.7
    - pip
  run:
    - typing_extensions >=4.12
    - psutil
    - pyocse >=0.1.1
    - vasprun-xml >=1.0.4
    - numpy >=1.26,<2
    - typing-extensions >=4.12
    - python <=3.12,>=3.7
    - spglib >=2.5.0
    - pymatgen >=2024.3.1
    - pandas >=2.0.2
    - networkx >=2.3
    - ase >=3.23.0
    - scipy >=1.7.3
    - importlib-metadata >=1.4
    - pyshtools >=4.10.3

test:
  imports:
    - pyxtal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qzhu2017/PyXtal
  summary: Python code for generation of crystal structures based on symmetry constraints.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
