{% set name = "pyxtal" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxtal-{{ version }}.tar.gz
  sha256: 2e77013bf99d6c2351b31cb3ec463f1ec324dce0d270d2f524ce0f29635fe573

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python <=3.12,>=3.7
    - pip
  run:
    - python <=3.12,>=3.7
    - spglib >=1.10.4
    - pymatgen >=2023.10.3
    - pandas >=2.0.2
    - networkx >=2.3
    - ase >=3.18.0
    - scipy >=1.7.3
    - importlib-metadata >=1.4
    - pyshtools >=4.10.3

test:
  imports:
    - pyxtal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qzhu2017/PyXtal
  summary: Python code for generation of crystal structures based on symmetry constraints.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
