{% set name = "pyxtal" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxtal-{{ version }}.tar.gz
  sha256: ec0c4ded02fe760947d9f02a2ba80221ccae342623ce8bf7847168ba1b428902
  patches:
    - python311.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - spglib >=1.10.4
    - pymatgen >=2022.0.12
    - pandas >=0.24.2
    - networkx >=2.3
    - py3dmol >=0.8.0
    - ase >=3.18.0
    - numba >=0.55.2
    - scipy >=1.7.3
    - importlib-metadata >=1.4
    - pyshtools ==4.10

test:
  imports:
    - pyxtal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qzhu2017/PyXtal
  summary: Python code for generation of crystal structures based on symmetry constraints.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
